using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;
using Photon.Realtime;
using System.Text.RegularExpressions;

public class NetworkManager : MonoBehaviourPunCallbacks
{
    private GameObject playerList;
    public GameObject[] mainvrCams;
    public GameObject[] mainkeyCams;

    public string pNum = "";
    public string ppNum = "";

    public string dNum;
    public RoomOptions options;
    public int tempNum;

    public Transform[] keyModelSpawn;

    public Stack<string> keyList = new Stack<string>();
    public Stack<string> vrList = new Stack<string>();
    private int i=0;
    private int vrplayernum=0;
    void Start()
    {
        /*vrList.Push("vr4");
        vrList.Push("vr3");
        vrList.Push("vr2");
        vrList.Push("vr1"); //vrListï¿½ï¿½ vr1~4ï¿½Ü‚ï¿½(ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½}ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒjï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½)ï¿½ï¿½ï¿½Xï¿½^ï¿½bï¿½Nï¿½ï¿½ï¿½Ü‚ï¿½
*/
        keyList.Push("key4");
        keyList.Push("key3");
        keyList.Push("key2");
        keyList.Push("key1"); //keyListï¿½ï¿½ key1~4ï¿½Ü‚ï¿½(ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½ï¿½Ìƒjï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½)ï¿½ï¿½ï¿½Xï¿½^ï¿½bï¿½Nï¿½ï¿½ï¿½Ü‚ï¿½

        //key1ModelSpawn = GameObject.Find("Key1ModelSpawn").GetComponent<Transform>(); //ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½ÌƒLï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½ï¿½Ê’u

        playerList = GameObject.Find("InputWorld"); //ï¿½Vï¿½[ï¿½ï¿½ï¿½uLobbyï¿½vï¿½ï¿½InputWorldï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g
        dNum = playerList.GetComponent<InputWorld>().deviceNum; //dNumï¿½ï¿½deviceNumï¿½u"1" or "2"ï¿½vï¿½É‚ï¿½ï¿½ï¿½

        PhotonNetwork.ConnectUsingSettings(); //Photonï¿½ÉÚ‘ï¿½ï¿½ï¿½ï¿½ï¿½
        options = new RoomOptions();
        options.PublishUserId = true; //UserIdï¿½ï¿½ï¿½J
        options.MaxPlayers = 8; //ï¿½Å‘ï¿½lï¿½ï¿½


        Invoke("checkNum", 5.0f); //5ï¿½bï¿½ï¿½ï¿½chekNum()ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½
    }

    void checkNum()
    {
        Debug.Log(pNum);
        if (pNum == "" && ppNum == "") //pNumï¿½ï¿½ppNumï¿½Ì’lï¿½ï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ê‡(ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½sï¿½Ìê‡)ï¿½A(ï¿½Äï¿½ï¿½sï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½ï¿½)ï¿½Qï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            Debug.Log("Failed to connect");
            //UnityEditor.EditorApplication.isPlaying = false;
        }
    }

    [PunRPC]
    void listkeyManage() //ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½ï¿½Ìê‡(ï¿½Lï¿½[ï¿½{ï¿½[ï¿½hï¿½ï¿½key)ï¿½AkeyListï¿½ï¿½ï¿½ï¿½jï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Âoï¿½ï¿½ï¿½ï¿½pNumï¿½É‚ï¿½ï¿½ï¿½
    {
        Debug.Log("listkeyManage");
        pNum = keyList.Pop();
        //GameObject.Find(pNum).SetActive(false);
    }

    [PunRPC]
    void listvrManage() //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½}ï¿½ï¿½ï¿½ï¿½ï¿½Ìê‡(vr)ï¿½AvrListï¿½ï¿½ï¿½ï¿½jï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Âoï¿½ï¿½ï¿½ï¿½ppNumï¿½É‚ï¿½ï¿½ï¿½
    {
        Debug.Log("listvrManage");
        //ppNum = vrList.Pop();
        vrplayernum++;
        ppNum=$"vr{vrplayernum}";
    }
    [PunRPC]
    void debugerlist() //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½}ï¿½ï¿½ï¿½ï¿½ï¿½Ìê‡(vr)ï¿½AvrListï¿½ï¿½ï¿½ï¿½jï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Âoï¿½ï¿½ï¿½ï¿½ppNumï¿½É‚ï¿½ï¿½ï¿½
    {
        ppNum = $"debuger{i}";
        i++;
    }





    public override void OnConnectedToMaster()
    {
        // "Room"ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Oï¿½Ìƒï¿½ï¿½[ï¿½ï¿½ï¿½ÉQï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½İ‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½Îì¬ï¿½ï¿½ï¿½ÄQï¿½ï¿½ï¿½ï¿½ï¿½ï¿½j
        PhotonNetwork.JoinOrCreateRoom("Room", options, TypedLobby.Default);
    }

    public override void OnJoinedRoom() //ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÉQï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½
    {
        Invoke("joinAndPlay", 1.0f);
    }

    void joinAndPlay()
    {
        if (dNum == "1") //ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½Sï¿½Ä‚Ìƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½listkeyManage()ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½
        {
            photonView.RPC(nameof(listkeyManage), RpcTarget.AllBuffered);
        }
        else if (dNum == "2") //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½}ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½Sï¿½Ä‚Ìƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½listvrManage()ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½
        {
            photonView.RPC(nameof(listvrManage), RpcTarget.AllBuffered);
        }
        else if (dNum == "3") //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½}ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½Sï¿½Ä‚Ìƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½listvrManage()ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½
        {
            photonView.RPC(nameof(debugerlist), RpcTarget.AllBuffered);
        }
        Invoke("setNick", 1.0f); //(PunRPCï¿½Éï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚ï¿½)1ï¿½bï¿½ï¿½ï¿½setNick()ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½
    }

    void setNick()
    {
        if (dNum == "1") //ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½Aï¿½jï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½Æ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½ï¿½ÌƒJï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½ê‚ªï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Æ‚È‚ï¿½)
        {
            PhotonNetwork.NickName = pNum; //ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½jï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½key1~4ï¿½É‚ï¿½ï¿½ï¿½
            tempNum = int.Parse(Regex.Replace(pNum, @"[^0-9]", ""));
            mainkeyCams[tempNum - 1].SetActive(true);
            
            if (PhotonNetwork.NickName == "key1") //ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒjï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ÉƒAï¿½oï¿½^ï¿½[ï¿½ğ•ª‚ï¿½ï¿½ÄŒÄ‚Ñoï¿½ï¿½
            {
                PhotonNetwork.Instantiate("key1", keyModelSpawn[0].position, keyModelSpawn[0].rotation);
                GameObject.Find("key Cam1").AddComponent(typeof(AudioListener));
            }
            if (PhotonNetwork.NickName == "key2") //ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒjï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ÉƒAï¿½oï¿½^ï¿½[ï¿½ğ•ª‚ï¿½ï¿½ÄŒÄ‚Ñoï¿½ï¿½
            {
                PhotonNetwork.Instantiate("key2", keyModelSpawn[1].position, keyModelSpawn[1].rotation);
                GameObject.Find("key Cam2").AddComponent(typeof(AudioListener));

            }
            if (PhotonNetwork.NickName == "key3") //ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒjï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ÉƒAï¿½oï¿½^ï¿½[ï¿½ğ•ª‚ï¿½ï¿½ÄŒÄ‚Ñoï¿½ï¿½
            {
                PhotonNetwork.Instantiate("key3", keyModelSpawn[2].position, keyModelSpawn[2].rotation);
                GameObject.Find("key Cam3").AddComponent(typeof(AudioListener));
            }
            if (PhotonNetwork.NickName == "key4") //ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒjï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ÉƒAï¿½oï¿½^ï¿½[ï¿½ğ•ª‚ï¿½ï¿½ÄŒÄ‚Ñoï¿½ï¿½
            {
                PhotonNetwork.Instantiate("key4", keyModelSpawn[3].position, keyModelSpawn[3].rotation);
                GameObject.Find("key Cam4").AddComponent(typeof(AudioListener));
            }



            /*PhotonNetwork.Instantiate("key2", keyModelSpawn[1].position, keyModelSpawn[1].rotation);
            GameObject.Find("key Cam1").AddComponent(typeof(AudioListener));
        */

        }
        else if (dNum == "2")
        {
            PhotonNetwork.NickName = ppNum; //ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½jï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½vr1~4ï¿½É‚ï¿½ï¿½ï¿½
            mainvrCams[0].SetActive(true); //XR Originï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g(ï¿½ï¿½ï¿½ê‚ªï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Æ‚È‚ï¿½)
            if (GameObject.Find("Main Camera1").GetComponent<AudioListener>() == null)
            {
                GameObject.Find("Main Camera1").AddComponent(typeof(AudioListener));
            }
            PhotonNetwork.Instantiate($"MainAvatar {(vrplayernum-1)%4+1}",new Vector3(0f, 0f, 0f), Quaternion.identity);
            /*
            if (PhotonNetwork.NickName == "vr1") //ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒjï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ÉƒAï¿½oï¿½^ï¿½[ï¿½ğ•ª‚ï¿½ï¿½ÄŒÄ‚Ñoï¿½ï¿½
            {
                PhotonNetwork.Instantiate("MainAvatar 1", new Vector3(0f, 0f, 0f), Quaternion.identity);
            }
            else if (PhotonNetwork.NickName == "vr2")
            {
                PhotonNetwork.Instantiate("MainAvatar 2", new Vector3(0f, 0f, 0f), Quaternion.identity);
            }
            else if (PhotonNetwork.NickName == "vr3")
            {
                PhotonNetwork.Instantiate("MainAvatar 3", new Vector3(0f, 0f, 0f), Quaternion.identity);
            }
            else if (PhotonNetwork.NickName == "vr4")
            {
                PhotonNetwork.Instantiate("MainAvatar 4", new Vector3(0f, 3f, 0f), Quaternion.identity);
            }
            */
        }
        else if (dNum == "3")
        {
            PhotonNetwork.NickName = ppNum; //ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½jï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½vr1~4ï¿½É‚ï¿½ï¿½ï¿½
            PhotonNetwork.Instantiate("debuger", new Vector3(0f, 3f, 0f), Quaternion.identity);
            
        }
    }
    void Update()
    {
        PhotonNetwork.SerializationRate = 10; //1ï¿½bï¿½ï¿½10ï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½ 
    }

    public override void OnLeftRoom() //ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Şê‚µï¿½ï¿½ï¿½ê‡ï¿½Aï¿½ï¿½ï¿½Xï¿½gï¿½Éï¿½ï¿½ï¿½ï¿½Ìƒjï¿½bï¿½Nï¿½lï¿½[ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½
    {
        if (dNum == "1")
        {
            //GameObject.Find(pNum).SetActive(true);
            keyList.Push(PhotonNetwork.NickName);
        }
        else if (dNum == "2")
        {
            //vrList.Push(PhotonNetwork.NickName);
        }
        else if (dNum == "3")
        {
            vrList.Push(PhotonNetwork.NickName);
        }
        else
        {

        }
        base.OnLeftRoom();
    }

}